# Generated by Django 2.2.9 on 2020-02-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bdd_consultants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_prenom', models.CharField(default=' ', max_length=400)),
                ('diminutif', models.CharField(default=' ', max_length=400)),
                ('telephone', models.CharField(default=' ', max_length=400)),
                ('mail', models.EmailField(max_length=254)),
                ('adresse', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Consultant',
            },
        ),
    ]
