# Generated by Django 2.2.9 on 2020-02-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_bdd_formateurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bdd_missions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('description', models.CharField(default=' ', max_length=400)),
                ('date', models.DateField(default=' ', max_length=400)),
            ],
            options={
                'verbose_name': 'Mission',
                'ordering': ['id'],
            },
        ),
    ]
