# Generated by Django 2.2.9 on 2020-02-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_bdd_missions'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd_missions',
            name='formateur',
            field=models.CharField(default=' ', max_length=400),
        ),
    ]
