# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-19 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_bdd_missions_formateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bdd_messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
                ('envoyeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envoyeur', to='planning.Bdd_consultants')),
                ('receveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receveur', to='planning.Bdd_consultants')),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['date'],
            },
        ),
    ]
