# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-20 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_bdd_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd_messages',
            name='lu',
            field=models.BooleanField(default=False),
        ),
    ]
