# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-05 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_auto_20200305_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdd_missions',
            options={'ordering': ['date', 'formateur'], 'verbose_name': 'Mission'},
        ),
        migrations.AlterField(
            model_name='bdd_missions',
            name='date',
            field=models.DateField(),
        ),
    ]
