# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-05 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_auto_20200305_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd_missions',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
