# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_auto_20200305_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdd_missions',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='bdd_missions',
            name='description',
            field=models.TextField(),
        ),
    ]
