# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-06 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_auto_20200306_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bdd_formateurs',
        ),
        migrations.RemoveField(
            model_name='bdd_messages',
            name='envoyeur',
        ),
        migrations.RemoveField(
            model_name='bdd_messages',
            name='receveur',
        ),
        migrations.DeleteModel(
            name='Bdd_missions',
        ),
        migrations.DeleteModel(
            name='Bdd_consultants',
        ),
        migrations.DeleteModel(
            name='Bdd_messages',
        ),
    ]
