# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0015_auto_20200306_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bdd_adresse_client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('adresse', models.CharField(default=' ', max_length=400)),
                ('code_postal', models.CharField(default=' ', max_length=400)),
                ('ville', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Adresse Client',
            },
        ),
        migrations.CreateModel(
            name='Bdd_client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('code_couleur', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Bdd_consultants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diminutif', models.CharField(default=' ', max_length=400)),
                ('telephone', models.CharField(default=' ', max_length=400)),
                ('adresse', models.CharField(default=' ', max_length=400)),
                ('permission', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Consultant',
            },
        ),
        migrations.CreateModel(
            name='Bdd_formateurs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Formateur',
            },
        ),
        migrations.CreateModel(
            name='Bdd_messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'envoi")),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Bdd_mission_type_client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Mission Type Client',
            },
        ),
        migrations.CreateModel(
            name='Bdd_missions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.CharField(default='', max_length=400)),
                ('date_fin', models.CharField(default='', max_length=400)),
                ('status', models.CharField(choices=[('A', 'En Attente'), ('C', 'En Cours'), ('T', 'Terminée')], default='', max_length=20)),
                ('visible_consultant', models.BooleanField(default='')),
                ('adresse', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planning.Bdd_adresse_client')),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planning.Bdd_client')),
                ('consultant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planning.Bdd_consultants')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Mission',
            },
        ),
        migrations.CreateModel(
            name='Bdd_piece_jointe_client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('document', models.FileField(upload_to='')),
                ('date_upload', models.DateField(default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Bdd_client')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Pièce Jointe Client',
            },
        ),
        migrations.CreateModel(
            name='Bdd_theme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Thème',
            },
        ),
        migrations.CreateModel(
            name='Bdd_user_django',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_de_compte', models.CharField(default=' ', max_length=400)),
                ('mdp', models.CharField(default=' ', max_length=400)),
                ('mail', models.EmailField(max_length=254)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('prenom', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'User Django',
            },
        ),
        migrations.AddField(
            model_name='bdd_mission_type_client',
            name='piece_jointe',
            field=models.ManyToManyField(blank=True, to='planning.Bdd_piece_jointe_client'),
        ),
        migrations.AddField(
            model_name='bdd_mission_type_client',
            name='theme',
            field=models.ManyToManyField(to='planning.Bdd_theme'),
        ),
        migrations.AddField(
            model_name='bdd_messages',
            name='envoyeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envoyeur', to='planning.Bdd_user_django'),
        ),
        migrations.AddField(
            model_name='bdd_messages',
            name='receveur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receveur', to='planning.Bdd_user_django'),
        ),
        migrations.AddField(
            model_name='bdd_consultants',
            name='theme_confirme',
            field=models.ManyToManyField(related_name='theme_confirme', to='planning.Bdd_theme'),
        ),
        migrations.AddField(
            model_name='bdd_consultants',
            name='theme_junior',
            field=models.ManyToManyField(related_name='theme_junior', to='planning.Bdd_theme'),
        ),
        migrations.AddField(
            model_name='bdd_consultants',
            name='theme_senior',
            field=models.ManyToManyField(related_name='theme_senior', to='planning.Bdd_theme'),
        ),
        migrations.AddField(
            model_name='bdd_consultants',
            name='user_django',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_django', to='planning.Bdd_user_django'),
        ),
        migrations.AddField(
            model_name='bdd_client',
            name='mission_type',
            field=models.ManyToManyField(to='planning.Bdd_mission_type_client'),
        ),
        migrations.AddField(
            model_name='bdd_adresse_client',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.Bdd_client'),
        ),
    ]
