# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-06 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0017_remove_bdd_client_mission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdd_client',
            name='mission_type',
            field=models.ManyToManyField(to='planning.Bdd_mission_type_client'),
        ),
    ]
