# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-06 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0018_bdd_client_mission_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bdd_formateurs',
        ),
    ]
