# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-08 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0019_delete_bdd_formateurs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdd_missions',
            options={'ordering': ['date_debut', 'consultant'], 'verbose_name': 'Mission'},
        ),
    ]
